apiVersion: v1
kind: Service
metadata:
  labels:
    app: card-one
  name: card-one
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: card-one