apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: transactions-ted-trigger
spec:
  broker: transactions-broker
  filter:
    attributes:
      type: tech.claudioed.transaction.ted.create
      source: tech.claudioed.transaction.file
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: transactions-ted-service