apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: transactions-ted-service
spec:
  template:
    metadata:
      name: transactions-ted-service-v1
      annotations:
        autoscaling.knative.dev/maxScale: "100"
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
        - image: claudioed/transactions-ted-service
          imagePullPolicy: Always
          resources:
            requests:
              memory: "10Mi"
              cpu: "100m"
            limits:
              memory: "20Mi"
              cpu: "200m"
          env:
            - name: BANK_ACCOUNT_HOST
              value: "http://bank-account.legacy.svc.cluster.local:8080"
            - name: DB_DATABASE
              value: "postgres"
            - name: DB_PASS
              value: "mysecretpassword"
            - name: DB_USER
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: "postgresql.database.svc.cluster.local"