apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: transactions-card-visa-service
spec:
  template:
    spec:
      containers:
        - image: claudioed/transactions-card-visa-service