apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: transactions-doc-service
spec:
  template:
    metadata:
      name: transactions-doc-service-v1
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "3"
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
        - image: claudioed/transactions-doc-service