apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bank-account
spec:
  template:
    metadata:
      name: bank-account-v1
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "3"
        autoscaling.knative.dev/target: "100"
    spec:
      containers:
        - image: claudioed/bank-account
          ports:
            - name: http1
              containerPort: 8080
              protocol: TCP