apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transaction-file-storage
  labels:
    app: transaction-file-generator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi